import type { Metadata } from "next";
import localFont from "next/font/local";
import ReactQueryProvider from "@/react-query/react-query-provider";

import { getCompaniesServer } from "@/app/api/companies/utils.server";
import { getJobTypesServer } from "@/app/api/job-types/utils.server";
import { getJobsServer } from "@/app/api/jobs/utils.server";

import Header from "@/components/header";
import Footer from "@/components/footer";

import AppStateProvider from "./layout.provider";

import "@/app/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [
    companies,
    jobs,
    jobTypes,
  ] = await Promise.all([
    getCompaniesServer(),
    getJobsServer(),
    getJobTypesServer(),
  ]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AppStateProvider
            {...{
              companies,
              jobs,
              jobTypes,
            }}
          >
            <div className="flex flex-col">
              <div className="min-h-screen flex flex-col">
                <Header />
                <main className="flex-1">
                  {children}
                </main>
              </div>
              <Footer />
            </div>
          </AppStateProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
