CREATE TYPE regions AS ENUM (
  'UNSKO_SANSKI_KANTON',
  'POSAVSKI_KANTON',
  'TUZLANSKI_KANTON',
  'ZENICKO_DOBOJSKI_KANTON',
  'BOSANSKO_PODRINJSKI_KANTON',
  'SREDNJOBOSANSKI_KANTON',
  'HERCEGOVACKO_NERETVANSKI_KANTON',
  'ZAPADNOHERCEGOVACKI_KANTON',
  'KANTON_SARAJEVO',
  'KANTON_10',
  'BANJALUCKA_REGIJA',
  'DOBOJSKO_BIJELJINSKA_REGIJA',
  'SARAJEVSKO_ZVORNICKA_REGIJA',
  'TREBINJSKO_FOCANSKA_REGIJA',
  'BRCKO_DISTRIKT'
);
